### ISSUE TITLE
Not compatible with 1.35

### ISSUE THREAD

**Issue by jdlrobson** [Killarnee/DarkCosmos#2]
There are several issues with the current skin in 1.35. Because of this I have marked the skin as unstable on MediaWiki.org for now and submitted a fix.

**Comment by eguiraud** [comment]
Hello,
is the fork by @jdlrobson the recommended way to go for use in 1.35?

In particular, the dropdown menus do not work unless the skin is in "mobile" mode, and that's a breaking issue. Is there any known workaround?

Thanks!

**Comment by eguiraud** [comment]
@jdlrobson even with your 1.35 branch I get the following error at the browser console (and dropdown menus don't work except in "mobile" mode):

```
Error: Unknown module: jquery.tabIndex
    sortDependencies https://tanadelmimic.it/w/load.php?lang=it&modules=startup&only=scripts&raw=1&skin=darkcosmos:8
    sortDependencies https://tanadelmimic.it/w/load.php?lang=it&modules=startup&only=scripts&raw=1&skin=darkcosmos:8
    resolveStubbornly https://tanadelmimic.it/w/load.php?lang=it&modules=startup&only=scripts&raw=1&skin=darkcosmos:9
    load https://tanadelmimic.it/w/load.php?lang=it&modules=startup&only=scripts&raw=1&skin=darkcosmos:20
    <anonymous> https://tanadelmimic.it/w/load.php?lang=it&modules=startup&only=scripts&raw=1&skin=darkcosmos:35
    <anonymous> https://tanadelmimic.it/w/load.php?lang=it&modules=startup&only=scripts&raw=1&skin=darkcosmos:35
```

Indeed the [release notes of MediaWiki 1.35](https://www.mediawiki.org/wiki/Release_notes/1.35) mention the module has been removed.

**Comment by eguiraud** [comment]
A workaround for the `tabIndex` problem is [here](https://github.com/Killarnee/DarkCosmos/commit/ff1a4435a1ea60e6d379769ec319089f2fec11d4) (not sure if it's the right fix, but works for me), @Killarnee let me know if you would like a pull request.
